(executables
 (names
  postgres_example
  redis_example
  basic_example
  mysql_example
  mariadb_example
  mongo_example
  kafka_example
  elasticsearch_example
  localstack_example
  memcached_example
  mockserver_example)
 (libraries
  testcontainers
  testcontainers-postgres
  testcontainers-redis
  testcontainers-mysql
  testcontainers-mariadb
  testcontainers-mongo
  testcontainers-kafka
  testcontainers-elasticsearch
  testcontainers-localstack
  testcontainers-memcached
  testcontainers-mockserver
  lwt
  lwt.unix)
 (preprocess
  (pps lwt_ppx)))
